// src/lib/sample-data.ts
import type { Product } from "@/types";

export const sampleProducts: Product[] = [
  {
    id: "1",
    name: "جراب سيليكون فاخر لآيفون 15 برو",
    description: "جراب سيليكون عالي الجودة يوفر حماية ممتازة وملمس ناعم لهاتف آيفون 15 برو. متوفر بألوان متعددة.",
    price: 250,
    images: ["https://picsum.photos/seed/case1/400/400", "https://picsum.photos/seed/case1_alt/400/400"],
    category: "جرابات",
  },
  {
    id: "2",
    name: "واقي شاشة زجاجي لسامسونج جالاكسي S24 ألترا",
    description: "واقي شاشة من الزجاج المقوى بدرجة صلابة 9H، مقاوم للخدوش والصدمات، ويحافظ على وضوح الشاشة.",
    price: 180,
    images: ["https://picsum.photos/seed/screenprotector1/400/400"],
    category: "واقيات شاشة",
  },
  {
    id: "3",
    name: "شاحن سريع 65 واط USB-C PD",
    description: "شاحن جداري بتقنية الشحن السريع Power Delivery، يدعم شحن اللابتوبات والهواتف المتوافقة بقوة تصل إلى 65 واط.",
    price: 450,
    images: ["https://picsum.photos/seed/charger1/400/400"],
    category: "شواحن",
  },
  {
    id: "4",
    name: "سماعات أذن لاسلكية بلوتوث 5.3",
    description: "سماعات أذن لاسلكية بصوت نقي وجودة عالية، تدعم بلوتوث 5.3 وتوفر عمر بطارية طويل.",
    price: 600,
    images: ["https://picsum.photos/seed/earbuds1/400/400", "https://picsum.photos/seed/earbuds1_alt/400/400"],
    category: "إكسسوارات صوت",
  },
  {
    id: "5",
    name: "كابل شحن USB-C إلى Lightning معتمد MFi",
    description: "كابل شحن ونقل بيانات معتمد من آبل، يضمن التوافق والأداء الأمثل مع أجهزة آيفون وآيباد.",
    price: 220,
    images: ["https://picsum.photos/seed/cable1/400/400"],
    category: "كوابل",
  },
  {
    id: "6",
    name: "حامل هاتف مغناطيسي للسيارة",
    description: "حامل هاتف قوي للسيارة يتم تثبيته على فتحة التهوية، يوفر تثبيتًا آمنًا وسهل الاستخدام.",
    price: 150,
    images: ["https://picsum.photos/seed/carholder1/400/400"],
    category: "حوامل",
  },
  {
    id: "7",
    name: "جراب شفاف مقاوم للصدمات لـ OnePlus 12",
    description: "جراب شفاف يبرز تصميم الهاتف مع توفير حماية قوية ضد السقوط والصدمات.",
    price: 200,
    images: ["https://picsum.photos/seed/case2/400/400"],
    category: "جرابات",
  },
  {
    id: "8",
    name: "باور بانك 20000 مللي أمبير",
    description: "بطارية متنقلة بسعة كبيرة 20000 مللي أمبير، تدعم الشحن السريع لأجهزة متعددة.",
    price: 750,
    images: ["https://picsum.photos/seed/powerbank1/400/400"],
    category: "شواحن",
  },
  {
    id: "9",
    name: "واقي شاشة خصوصية لآيفون 14",
    description: "يحمي شاشتك من الخدوش ومن أعين المتطفلين، مصنوع من زجاج مقوى عالي الجودة.",
    price: 210,
    images: ["https://picsum.photos/seed/privacyfilm/400/400"],
    category: "واقيات شاشة",
  },
  {
    id: "10",
    name: "كابل USB-A إلى USB-C مضفر",
    description: "كابل شحن ونقل بيانات متين ومضفر، بطول 1.5 متر، مثالي للاستخدام اليومي.",
    price: 120,
    images: ["https://picsum.photos/seed/cablebraided/400/400"],
    category: "كوابل",
  },
  {
    id: "11",
    name: "سماعة رأس فوق الأذن لاسلكية",
    description: "سماعات رأس مريحة بصوت غامر، تعمل بتقنية البلوتوث مع ميكروفون مدمج للمكالمات.",
    price: 950,
    images: ["https://picsum.photos/seed/headphonesoverear/400/400"],
    category: "إكسسوارات صوت",
  },
  {
    id: "12",
    name: "حامل مكتب للهاتف والتابلت",
    description: "حامل أنيق وقابل للتعديل للهواتف والأجهزة اللوحية، مثالي للمكتب أو المنزل.",
    price: 180,
    images: ["https://picsum.photos/seed/desktophstand/400/400"],
    category: "حوامل",
  },
  {
    id: "13",
    name: "منظف شاشة متعدد الأغراض",
    description: "مجموعة تنظيف للشاشات، تزيل البصمات والغبار بأمان، مناسبة للهواتف واللابتوبات.",
    price: 90,
    images: ["https://picsum.photos/seed/screencleaner/400/400"],
    category: "أخرى",
  },
  {
    id: "14",
    name: "جراب جلد طبيعي لجوجل بيكسل 8",
    description: "جراب فاخر مصنوع من الجلد الطبيعي، يوفر حماية أنيقة لهاتف جوجل بيكسل 8.",
    price: 350,
    images: ["https://picsum.photos/seed/leathercasepixel/400/400"],
    category: "جرابات",
  },
  {
    id: "15",
    name: "شاحن سيارة سريع بمنفذين USB",
    description: "شاحن سيارة مدمج وقوي، يدعم الشحن السريع لجهازين في نفس الوقت.",
    price: 280,
    images: ["https://picsum.photos/seed/carcharger/400/400"],
    category: "شواحن",
  },
  {
    id: "16",
    name: "محول USB-C إلى مقبس سماعة 3.5 ملم",
    description: "محول صغير وعملي لتوصيل سماعات الرأس التقليدية بأجهزة USB-C الحديثة.",
    price: 130,
    images: ["https://picsum.photos/seed/usbcadapteraudio/400/400"],
    category: "أخرى",
  },
  {
    id: "17",
    name: "واقي عدسة كاميرا لآيفون 15 برو ماكس",
    description: "يحمي عدسات الكاميرا من الخدوش والصدمات دون التأثير على جودة التصوير.",
    price: 95,
    images: ["https://picsum.photos/seed/cameraprotector/400/400"],
    category: "واقيات شاشة",
  },
  {
    id: "18",
    name: "كابل HDMI عالي السرعة 2 متر",
    description: "كابل HDMI يدعم دقة 4K لنقل الصوت والصورة بجودة عالية.",
    price: 170,
    images: ["https://picsum.photos/seed/hdmicable/400/400"],
    category: "كوابل",
  },
  {
    id: "19",
    name: "مكبر صوت بلوتوث محمول مقاوم للماء",
    description: "مكبر صوت صغير وقوي، مقاوم للماء ومثالي للاستخدام في الخارج.",
    price: 400,
    images: ["https://picsum.photos/seed/bluetoothspeaker/400/400"],
    category: "إكسسوارات صوت",
  },
  {
    id: "20",
    name: "عصا سيلفي مع ترايبود مدمج",
    description: "عصا سيلفي متعددة الاستخدامات مع حامل ثلاثي مدمج وريموت بلوتوث.",
    price: 220,
    images: ["https://picsum.photos/seed/selfiestick/400/400"],
    category: "أخرى",
  },
  {
    id: "21",
    name: "جراب محفظة جلد لهاتف سامسونج",
    description: "جراب عملي بتصميم محفظة يوفر حماية للهاتف ومساحة للبطاقات والنقود.",
    price: 280,
    images: ["https://picsum.photos/seed/walletcase/400/400"],
    category: "جرابات",
  },
  {
    id: "22",
    name: "قلم لمس للهواتف والأجهزة اللوحية",
    description: "قلم لمس دقيق وسلس، متوافق مع جميع شاشات اللمس.",
    price: 110,
    images: ["https://picsum.photos/seed/styluspen/400/400"],
    category: "أخرى",
  },
  {
    id: "23",
    name: "لوحة شحن لاسلكي سريعة 15 واط",
    description: "قاعدة شحن لاسلكي أنيقة تدعم الشحن السريع بقدرة 15 واط للأجهزة المتوافقة.",
    price: 320,
    images: ["https://picsum.photos/seed/wirelesschargerpad/400/400"],
    category: "شواحن",
  }
];
